// Turns a photo into the data behind the particle portrait on ethchor.qwantarc.com.
// The photo itself never ships: only a small grid of brightness and warmth values does.
//
//   node scripts/portrait.mjs path/to/photo.jpg
//
// Writes src/lib/ethchor/portrait.ts. Tuned for a head-and-shoulders photo against greenery.
import sharp from 'sharp';
import { writeFileSync } from 'node:fs';

const src = process.argv[2];
if (!src) throw new Error('Usage: node scripts/portrait.mjs photo.jpg');

const COLS = 96;
const ROWS = 128;
// Work at twice the output size, then average down.
const W = COLS * 2;
const H = ROWS * 2;

const { data } = await sharp(src)
  .rotate()
  .extract({ left: 150, top: 20, width: 900, height: 1200 })
  .resize(W, H, { kernel: 'lanczos3' })
  .removeAlpha()
  .raw()
  .toBuffer({ resolveWithObject: true });

const lum = new Float32Array(W * H);
const warm = new Float32Array(W * H);
let mask = new Float32Array(W * H);
for (let i = 0; i < W * H; i++) {
  const r = data[i * 3];
  const g = data[i * 3 + 1];
  const b = data[i * 3 + 2];
  const l = 0.2126 * r + 0.7152 * g + 0.0722 * b;
  lum[i] = l;
  // Sunlit olive greenery (green about as strong as red, little blue) and the pale grey water
  // behind are background. Skin is far redder than green; the navy hoodie is bluer than both.
  const olive = g >= r - 12 && b < g - 20;
  const grey = Math.max(r, g, b) - Math.min(r, g, b) < 30 && l > 95 && b <= g + 2;
  // Khaki trunks and dry grass: red only a little above green. Skin is 50 or more above.
  const khaki = r - g < 32 && g - b > 18 && l > 80;
  mask[i] = olive || grey || khaki ? 0 : 1;
  warm[i] = Math.max(0, Math.min(1, (r - g) / 50)) * Math.max(0, Math.min(1, (l - 50) / 90));
}

// Smooth the mask so stray speckles drop out and edges stay clean.
const blur = (src, radius) => {
  const out = new Float32Array(W * H);
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      let s = 0;
      let n = 0;
      for (let dy = -radius; dy <= radius; dy++) {
        for (let dx = -radius; dx <= radius; dx++) {
          const xx = x + dx;
          const yy = y + dy;
          if (xx < 0 || yy < 0 || xx >= W || yy >= H) continue;
          s += src[yy * W + xx];
          n++;
        }
      }
      out[y * W + x] = s / n;
    }
  }
  return out;
};
mask = blur(mask, 3).map((v) => (v > 0.5 ? 1 : 0));

// Keep only the largest connected shape, the person; patches of background drop away.
{
  const label = new Int32Array(W * H).fill(-1);
  let best = -1;
  let bestSize = 0;
  let next = 0;
  for (let i = 0; i < W * H; i++) {
    if (!mask[i] || label[i] >= 0) continue;
    const stack = [i];
    label[i] = next;
    let size = 0;
    while (stack.length) {
      const j = stack.pop();
      size++;
      const x = j % W;
      const y = (j - x) / W;
      for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
        const xx = x + dx;
        const yy = y + dy;
        if (xx < 0 || yy < 0 || xx >= W || yy >= H) continue;
        const k = yy * W + xx;
        if (mask[k] && label[k] < 0) {
          label[k] = next;
          stack.push(k);
        }
      }
    }
    if (size > bestSize) {
      bestSize = size;
      best = next;
    }
    next++;
  }
  for (let i = 0; i < W * H; i++) mask[i] = label[i] === best ? 1 : 0;
}
mask = blur(mask, 2);

// Stretch brightness across the person only, so the face spans the full range.
const inside = [];
for (let i = 0; i < W * H; i++) if (mask[i] > 0.5) inside.push(lum[i]);
inside.sort((a, b) => a - b);
const lo = inside[Math.floor(inside.length * 0.02)];
const hi = inside[Math.floor(inside.length * 0.985)];

const outLum = new Uint8Array(COLS * ROWS);
const outWarm = new Uint8Array(COLS * ROWS);
for (let y = 0; y < ROWS; y++) {
  for (let x = 0; x < COLS; x++) {
    let l = 0;
    let w = 0;
    let m = 0;
    for (const [dx, dy] of [[0, 0], [1, 0], [0, 1], [1, 1]]) {
      const i = (y * 2 + dy) * W + (x * 2 + dx);
      l += lum[i];
      w += warm[i];
      m += mask[i];
    }
    l /= 4;
    w /= 4;
    m /= 4;
    const o = y * COLS + x;
    const ex = (x / COLS - 0.5) / 0.62;
    const ey = (y / ROWS - 0.44) / 0.66;
    m *= Math.max(0, Math.min(1, (1 - (ex * ex + ey * ey)) * 2.2));
    if (m < 0.35) continue;
    const t = Math.max(0, Math.min(1, (l - lo) / (hi - lo)));
    // 0 means "no dot"; the person always gets at least 1, so hair and hoodie still show.
    outLum[o] = 1 + Math.round(t * 254 * Math.min(1, m * 1.4));
    outWarm[o] = Math.round(Math.min(1, w) * 255);
  }
}

const b64 = (u8) => Buffer.from(u8).toString('base64');
writeFileSync(
  new URL('../src/lib/ethchor/portrait.ts', import.meta.url),
  `/**
 * The particle portrait's data, generated by scripts/portrait.mjs from a photo that is not shipped.
 * A ${COLS} by ${ROWS} grid, row by row: brightness (0 is background, 1 to 255 the person) and
 * warmth (how skin-like the colour is, 0 to 255).
 */
export const PORTRAIT = {
  cols: ${COLS},
  rows: ${ROWS},
  lum: '${b64(outLum)}',
  warm: '${b64(outWarm)}',
};
`,
);
if (process.argv[3]) {
  const S = 6;
  const dots = [];
  for (let y = 0; y < ROWS; y++) {
    for (let x = 0; x < COLS; x++) {
      const v = outLum[y * COLS + x];
      if (!v) continue;
      const t = v / 255;
      const r = (S / 2) * (0.16 + 0.84 * Math.pow(t, 0.85));
      const w = outWarm[y * COLS + x] / 255;
      const c = [Math.round(236 + w * 19), Math.round(233 - w * 50), Math.round(227 - w * 90)];
      dots.push(`<circle cx="${x * S + S / 2}" cy="${y * S + S / 2}" r="${r.toFixed(2)}" fill="rgb(${c})"/>`);
    }
  }
  await sharp(Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${COLS * S}" height="${ROWS * S}"><rect width="100%" height="100%" fill="#0a0a09"/>${dots.join('')}</svg>`))
    .png()
    .toFile(process.argv[3]);
}
const people = outLum.filter((v) => v > 0).length;
console.log(`portrait: ${COLS}x${ROWS}, ${people} dots on the person (${Math.round((people / outLum.length) * 100)}%)`);
